name: crucible2csv
version: 0.85.0
description: >-
  TBD
author: Mike Chambers <mikechambers@gmail.com>
homepage: https://www.mikechambers.com
dependencies:
  args: ^1.5.1
environment:
  sdk: '>=2.0.0 <3.0.0'

